import { test } from 'node:test';
import { chrome } from './helpers/browser.js';
import { fixture } from './helpers/editing-fixture.js';
import { checkInteractiveBrowser } from './helpers/interactive-browser.js';

const script = String.raw`
import { act } from 'react';
import { createRoot } from 'react-dom/client';
import { App } from './src/panel/app.tsx';
import { state } from 'editing-fixture';
globalThis.IS_REACT_ACT_ENVIRONMENT = true;
const intervals = new Map(); let timer = 0;
window.setInterval = callback => { intervals.set(++timer, callback); return timer; };
window.clearInterval = id => intervals.delete(id);
const check = (ok, message) => { if (!ok) throw Error(message); };
const action = async fn => { await act(async () => { await fn(); await new Promise(r => setTimeout(r, 100)); }); await new Promise(r => setTimeout(r, 180)); };
const input = options => action(() => window.browserInput(options));
const pointer = (id, type, fraction = 0.5) => input({ pointer: { selector: '[row-id="' + id + '"] [col-id="order"]', type, fraction } });
const refresh = () => action(() => [...intervals.values()].forEach(fn => fn()));
const order = ids => check(state.status.snapshot.segments.map(s => s.id).join() === ids, '项目顺序应为 ' + ids);
(async () => { try {
  state.status.snapshot.segments = Array.from({length: 6}, (_, i) => ({id: String(i+1), order:i+1,text:'片段 '+(i+1),video:null}));
  await action(() => createRoot(document.getElementById('root')).render(<App />));
  await input({click:'[col-id="order"] .ag-header-cell-label'});
  await input({click:'[col-id="order"] .ag-header-cell-label'});
  check(document.querySelector('[row-id="1"]').getAttribute('row-index') === '0', '列标题不能改变项目顺序');
  await input({click:'[row-id="2"] input[type="checkbox"]'});
  await input({click:'[row-id="4"] input[type="checkbox"]'});
  await input({pointer:{selector:'[row-id="4"] .segment-drag-handle',type:'mousePressed'}});
  await pointer('5','mouseMoved',0.8);
  check(document.querySelector('[aria-label="口播片段插入位置"]'), '实际指针拖拽显示插入线');
  await window.browserInput({screenshot:'drag-insertion'});
  await pointer('5','mouseReleased',0.8);
  order('1,3,5,2,4,6');
  const original = Array.from({length:6},(_,i)=>({id:String(i+1),order:i+1,text:'片段 '+(i+1),video:i===1?{assetId:'video-2',start:3}:null}));
  const reset = async () => { state.status.snapshot.segments = structuredClone(original); await refresh(); await input({click:'[row-id="1"] [col-id="text"]'}); await input({key:'Escape'}); };
  const begin = id => input({pointer:{selector:'[row-id="'+id+'"] .segment-drag-handle',type:'mousePressed'}});
  const drag = async (from,to,fraction=0.8) => { await begin(from); await pointer(to,'mouseMoved',fraction); await pointer(to,'mouseReleased',fraction); await refresh(); };
  await reset();
  await input({click:'[row-id="2"] input[type="checkbox"]'}); await input({click:'[row-id="4"] input[type="checkbox"]'});
  await drag('2','5'); order('1,3,5,2,4,6');
  check(state.status.snapshot.segments.find(s=>s.id==='2').video.start===3, '重排保留画面素材关联');
  await reset();
  await input({click:'[row-id="2"] input[type="checkbox"]'}); await input({click:'[row-id="4"] input[type="checkbox"]'});
  await drag('6','1',0.2); order('6,1,2,3,4,5');
  check(state.selectionRequests.at(-1).join()==='6','未勾选拖动仅选中该行');
  await drag('6','5'); order('1,2,3,4,5,6');
  await input({click:'[row-id="2"] [col-id="text"]'}); await input({click:'[row-id="3"] [col-id="text"]',ctrl:true});
  await drag('3','1',0.2); order('2,3,1,4,5,6');
  const saves=state.saves;
  await drag('2','1',0.2); check(state.saves===saves,'最终顺序不变不提交');
  await begin('2'); await pointer('6','mouseMoved'); await input({key:'Escape'}); await pointer('6','mouseReleased');
  check(state.saves===saves,'Escape 取消不提交');
  await drag('2','3'); check(state.saves===saves,'自身位置不提交');
  await begin('2'); await pointer('6','mouseMoved'); state.status.taskLocked=true; await refresh(); await pointer('6','mouseReleased');
  check(state.saves===saves && document.querySelector('footer').textContent.includes('拖拽未提交'),'期间锁定明确拒绝');
  state.status.taskLocked=false; await reset();
  await begin('2'); await pointer('5','mouseMoved');
  state.status.snapshot.segments=[...state.status.snapshot.segments].reverse(); await refresh(); await pointer('5','mouseReleased');
  check(state.saves===saves && document.querySelector('footer').textContent.includes('顺序已变化'),'期间顺序变化拒绝且不覆盖');
  state.status.snapshot.segments=Array.from({length:100},(_,i)=>({id:String(i+1),order:i+1,text:'长表格片段 '+(i+1),video:null})); await refresh();
  await input({click:'[row-id="1"] [col-id="text"]'}); await begin('1');
  await pointer('5','mouseMoved');
  await input({pointer:{selector:'.ag-grid-viewport',type:'mouseWheel',buttons:1,deltaY:4000}});
  await action(()=>new Promise(r=>setTimeout(r,400)));
  const visible = [...document.querySelectorAll('.ag-row[row-id]')].find(row=>{ const r=row.getBoundingClientRect(); return r.top>180 && r.bottom<600; });
  check(visible && Number(visible.getAttribute('row-id'))>30,'真实滚轮滚动后虚拟目标已经可见');
  const target = visible.getAttribute('row-id'); await pointer(target,'mouseMoved',0.8);
  check(document.querySelector('[aria-label="口播片段插入位置"]').dataset.targetId===target,'长表格插入线采用稳定身份');
  await window.browserInput({screenshot:'drag-virtual-scroll'});
  await pointer(target,'mouseReleased',0.8);
  const ids=state.status.snapshot.segments.map(s=>s.id); check(ids.indexOf('1')===ids.indexOf(target)+1,'虚拟滚动后拖拽放置正确');
  document.getElementById('result').dataset.state='passed';
} catch(error) { document.getElementById('result').dataset.state='failed'; document.getElementById('result').textContent=error.stack; } })();
`;
for (const width of [1600, 420]) test('真实指针整体拖拽口播片段并保持项目顺序 '+width, {skip: chrome ? false : '未执行：需要 Chrome/Chromium', timeout:60000}, t => checkInteractiveBrowser(t, script, fixture, width));
