import { test } from 'node:test';
import { chrome } from './helpers/browser.js';
import { fixture } from './helpers/editing-fixture.js';
import { checkInteractiveBrowser } from './helpers/interactive-browser.js';

for (const width of [1600, 420]) test(`主视图全片导出与取消错误跨详情和连接恢复持续可见（${width}px）`, {
  skip: chrome ? false : '未执行：需要 Chrome/Chromium', timeout: 30000,
}, t => checkInteractiveBrowser(t, String.raw`
  import { act } from 'react';
  import { createRoot } from 'react-dom/client';
  import { App } from './src/panel/app.tsx';
  import { state } from 'editing-fixture';
  globalThis.IS_REACT_ACT_ENVIRONMENT = true;
  const intervals = new Map(); let timer = 0;
  window.setInterval = callback => { intervals.set(++timer, callback); return timer; };
  window.clearInterval = id => intervals.delete(id);
  const result = document.getElementById('result');
  const check = (value, message) => { if (!value) throw Error(message); };
  const settle = () => new Promise(resolve => setTimeout(resolve, 50));
  const button = text => [...document.querySelectorAll('button')].find(node => node.textContent === text);
  const click = async text => { await act(async () => { const node = button(text); check(node && !node.disabled, '按钮可用：' + text); node.focus(); node.click(); await settle(); }); await settle(); };
  const poll = async () => { await act(async () => { [...intervals.values()].forEach(callback => callback()); await settle(); }); await settle(); };
  const alerts = () => [...document.querySelectorAll('footer [role="alert"]')].map(node => node.textContent).join('\n');
  const shot = screenshot => window.browserInput({ screenshot });
  (async () => {
    try {
      state.status.snapshot.segments.push({ id: 'second', order: 2, text: '隐藏片段', video: null });
      await act(async () => { createRoot(document.getElementById('root')).render(<App />); await settle(); }); await settle();
      await act(async () => { document.querySelector('[row-id="segment"] input[type="checkbox"]').click(); });
      await click('查找');
      const filter = document.querySelector('[aria-label="查找文案"]');
      await act(async () => { Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(filter, '原文'); filter.dispatchEvent(new Event('input', { bubbles: true })); });
      check(document.getElementById('export-scope').textContent.includes('查找与勾选不改变范围'), '全项目导出范围明确');
      state.submitFailure = true; await click('导出全片');
      check(alerts().includes('Codex 正在修改'), '提交失败在状态栏可见');
      filter.focus(); await poll(); check(document.activeElement === filter && !document.querySelector('dialog'), '错误及任务更新不自动弹层或抢焦点');
      state.exportFailure = true; state.statusFailure = true; await poll();
      check(alerts().includes('读取导出任务失败') && alerts().includes('Codex 正在修改') && alerts().includes('服务连接失败'), '不同错误分别保留');
      state.exportFailure = false; state.statusFailure = false; await poll();
      check(!alerts().includes('读取导出任务失败') && !alerts().includes('服务连接失败') && alerts().includes('Codex 正在修改'), '连接恢复只清除对应连接错误');
      await click('更多'); await click('任务记录'); await click('关闭任务记录');
      check(alerts().includes('Codex 正在修改'), '关闭与重开任务详情不清除操作错误');
      state.submitFailure = false; await click('导出全片');
      check(!alerts(), '再次成功操作清除旧错误');
      check(state.exportRequests.length === 2 && state.exportRequests.every(args => args.length === 1), '提交始终只传项目服务地址，不传勾选或查找范围');
      state.exports = { locked: true, tasks: [{ id: 'export-1', state: 'rendering', completed: 1, total: 2, createdAt: '2026-10-03T00:00:00Z', message: '正在导出全片', issues: [], warnings: [] }] };
      state.status.taskLocked = true; await poll();
      check(button('导出全片').disabled && button('新增口播片段').disabled && document.querySelector('footer').textContent.includes('项目已锁定'), '项目锁定与重复请求保护保持');
      await shot('task-running');
      await click('任务详情'); state.cancelFailure = true; await click('取消导出'); await click('关闭任务记录');
      const count = state.exportQueries; await poll(); check(state.exportQueries > count, '关闭详情后继续轮询');
      check(alerts().includes('取消导出失败'), '关闭后取消失败仍可见');
      await shot('operation-error');
      state.exportFailure = true; await poll(); state.exportFailure = false; await poll();
      check(alerts().includes('取消导出失败'), '取消失败跨连接恢复保留');
      await click('任务详情'); check(document.querySelector('dialog').textContent.includes('任务 export-1'), '可查看标识');
      state.cancelFailure = false; await click('取消导出'); check(!alerts(), '再次成功取消清除旧错误');
      await click('关闭任务记录');
      state.status.taskLocked = false; state.exports.locked = false;
      state.exports.tasks[0] = { ...state.exports.tasks[0], state: 'succeeded', completed: 2, output: { path: '/tmp/movie.mp4', url: '/movie.mp4', previewUrl: '/preview.mp4' } }; await poll();
      await click('任务详情');
      check(document.querySelector('a[download]').getAttribute('href') === '/movie.mp4' && document.querySelector('a[target="_blank"]').getAttribute('href') === '/preview.mp4', '成片打开与下载入口保持');
      await click('关闭任务记录');
      state.speech = { locked: true, configured: true, configPath: '/tmp/config', voice: { speaker: 'zh_female_vv_uranus_bigtts', speechRate: 0 }, audio: [], tasks: [{ id: 'speech-1', requestId: 'request-1', segmentId: 'second', state: 'unknown', message: '结果未知，可能已计费' }], operations: [{ id: 'batch-1', request: { requestId: 'batch-request' }, summary: { completed: 1, succeeded: 0, failed: 0, interrupted: 1, pending: 1, skipped: 0, rejected: 0 }, results: [] }] };
      state.exports.tasks[0] = { ...state.exports.tasks[0], state: 'failed', message: '导出失败', output: null };
      filter.focus(); await poll();
      check(alerts().includes('结果未知，可能已计费') && alerts().includes('导出失败') && document.activeElement === filter, '未匹配片段的异常依然可见且不抢焦点');
      check(document.querySelector('footer').textContent.includes('配音 1/2'), '进行中的批量配音以紧凑进度常驻');
      await shot('persistent-error');
      await click('更多'); check(button('导入本地视频').disabled && button('粘贴多行文案').disabled, '迁移入口沿用禁用条件'); await click('任务记录');
      check(document.querySelector('dialog').textContent.includes('request-1') && document.querySelector('dialog').textContent.includes('batch-request'), '配音请求与批量进度详情可访问');
      await shot('task-details'); await click('关闭任务记录');
      state.selectionFailure = true;
      await act(async () => { document.querySelector('[row-id="segment"] input[type="checkbox"]').click(); await settle(); });
      check(alerts().includes('勾选连接已断开'), '勾选同步异常持续可见');
      await poll(); check(alerts().includes('勾选连接已断开'), '项目轮询不能清除勾选异常');
      state.selectionFailure = false; await click('重新连接勾选');
      check(!alerts().includes('勾选连接已断开'), '主动重连后清除对应异常');
      state.exports.tasks = [{ ...state.exports.tasks[0], id: 'older-failure', state: 'failed', message: '较早导出的具体失败原因' }, ...Array.from({ length: 5 }, (_, index) => ({ ...state.exports.tasks[0], id: 'success-' + index, state: 'succeeded', message: '导出成功' }))];
      await poll(); await click('任务详情');
      check(document.querySelector('dialog').textContent.includes('older-failure') && document.querySelector('dialog').textContent.includes('较早导出的具体失败原因'), '底部引用的较早失败必须仍可查看标识和错误');
      await click('关闭任务记录');
      result.dataset.state = 'passed';
    } catch (error) { result.dataset.state = 'failed'; result.textContent = error.stack; }
  })();
`, fixture, width));
