import assert from 'node:assert/strict';
import { test } from 'node:test';
import { chrome } from './helpers/browser.js';
import { fixture } from './helpers/editing-fixture.js';
import { checkInteractiveBrowser } from './helpers/interactive-browser.js';

for (const [width, height] of [[1600, 1000], [420, 800], [420, 360]]) test(`更多到任务与诊断的完整键盘链（${width}×${height}）`, { timeout: 40000 }, t => {
  assert.ok(chrome, '验收必须实际运行 Chrome');
  return checkInteractiveBrowser(t, String.raw`
    import { act } from 'react';
    import { createRoot } from 'react-dom/client';
    import { App } from './src/panel/app.tsx';
    import { assertTheme, assertKeyboardFocus } from './tests/helpers/theme-contract.ts';
    import { state, deferred } from 'editing-fixture';
    globalThis.IS_REACT_ACT_ENVIRONMENT = true;
    const intervals = new Map(); let timer = 0;
    window.setInterval = callback => { intervals.set(++timer, callback); return timer; };
    window.clearInterval = id => intervals.delete(id);
    const check = (value, message) => { if (!value) throw Error(message); };
    const settle = () => new Promise(resolve => setTimeout(resolve, 60));
    const button = text => [...document.querySelectorAll('button')].find(node => node.textContent === text);
    const click = async text => { await act(async () => { const node = button(text); check(node && !node.disabled, '入口可用：' + text); node.focus(); node.click(); await settle(); }); await settle(); };
    const key = async (key, shift = false) => { await act(async () => { await window.browserInput({ key, shift }); await settle(); }); await settle(); };
    const poll = async () => { await act(async () => { [...intervals.values()].forEach(callback => callback()); await settle(); }); };
    const dialog = () => document.querySelector('[role="dialog"][aria-modal="true"]');
    const bounds = () => { const d = dialog(), r = d.getBoundingClientRect(); check(r.left >= 0 && r.right <= innerWidth && r.top >= 0 && r.bottom <= innerHeight && d.scrollWidth <= d.clientWidth, '长内容不撑破视口'); };
    (async () => { try {
      state.status.snapshot.project.directory = '/tmp/' + '很长的工作空间路径'.repeat(30);
      await act(async () => { createRoot(document.getElementById('root')).render(<App />); await settle(); }); await settle();
      await click('更多');
      check(dialog() && document.getElementById(dialog().getAttribute('aria-labelledby'))?.textContent === '更多操作', '更多由统一弹窗可见标题命名');
      assertTheme('dialog', dialog()); assertTheme('cancel', button('粘贴多行文案'));
      await key('Tab'); await new Promise(resolve => setTimeout(resolve, 200)); assertKeyboardFocus(document.activeElement);
      button('粘贴多行文案').focus(); state.status.taskLocked = true; await poll();
      check(button('粘贴多行文案').disabled && document.activeElement === dialog(), '动态禁用后焦点回到容器');
      await new Promise(resolve => setTimeout(resolve, 200)); assertTheme('disabled', button('粘贴多行文案'));
      state.status.taskLocked = false; await poll();
      await click('声音设置');
      check(dialog().contains(document.activeElement), '更多向声音浮层交接焦点');
      await key('Escape'); check(document.activeElement === button('更多'), '旧浮层关闭恢复更多');
      state.exports.tasks = [{ id: 'result', state: 'failed', completed: 1, total: 2, createdAt: '2026-10-03T00:00:00Z', message: '导出失败', issues: [{ order: 1, segmentId: 'segment', message: '缺少有效配音' }], warnings: [{ order: 2, message: '使用静帧补齐' }], output: { path: '/tmp/' + '很长的成片位置'.repeat(25) + '.mp4', url: '/movie.mp4', previewUrl: '/preview.mp4' } }]; await poll();
      await click('更多'); await click('任务记录');
      check(dialog() && !button('声音设置') && document.activeElement === dialog(), '关闭更多并向任务容器交接焦点');
      const issue = [...dialog().querySelectorAll('li')].find(n => n.textContent.includes('缺少有效配音'));
      check(issue && getComputedStyle(issue).color === 'rgb(164, 38, 44)', '错误列表有明确错误主题');
      const warning = [...dialog().querySelectorAll('li')].find(n => n.textContent.includes('使用静帧补齐'));
      check(warning && getComputedStyle(warning.parentElement).listStyleType === 'disc' && parseFloat(getComputedStyle(warning.parentElement).paddingLeft) > 0, '警告列表有明确缩进和项目符号');
      const preview = dialog().querySelector('a[target="_blank"]'), download = dialog().querySelector('a[download]');
      check(preview.getAttribute('href') === '/preview.mp4' && download.getAttribute('href') === '/movie.mp4', '成片链接保持目的地址');
      for (const link of [preview, download]) check(getComputedStyle(link).color === 'rgb(8, 117, 209)' && getComputedStyle(link).textDecorationLine.includes('underline'), '成片链接清晰可辨');
      bounds(); await window.browserInput({ screenshot: 'tasks-' + innerHeight });
      state.exports.tasks[0].state = 'rendering'; state.exports.tasks[0].output = null; await poll();
      state.cancelGate = deferred(); await click('取消导出');
      check(button('取消导出').disabled && document.activeElement === dialog(), '取消请求中按钮禁用且焦点有后备');
      await act(async () => { state.cancelGate.resolve(); state.cancelGate = null; await settle(); });
      check(state.mutations.includes('取消导出') && !button('取消导出').disabled, '取消沿用现有请求并在结束后恢复');
      state.exports.tasks[0].state = 'cleaning'; await poll(); check(!button('取消导出'), '清理阶段不提供重复取消');
      for (let i = 0; i < 6; i++) { await key('Tab', i > 2); check(dialog().contains(document.activeElement), '正反向 Tab 保持模态范围'); }
      await act(async () => { await window.browserInput({ pointer: { type: 'mousePressed', x: 2, y: 2 } }); await window.browserInput({ pointer: { type: 'mouseReleased', x: 2, y: 2 } }); await settle(); });
      check(dialog(), '遮罩不关闭任务记录'); bounds();
      await click('连接诊断');
      check(document.getElementById(dialog().getAttribute('aria-labelledby'))?.textContent === '连接诊断', '任务到诊断保持名称');
      for (const label of ['面板版本', '服务版本', '版本核对', '项目路径', '服务实例', 'PID']) check([...dialog().querySelectorAll('dt')].some(n => n.textContent === label), '诊断信息完整：' + label);
      check(dialog().textContent.includes(state.status.snapshot.project.directory), '长工作空间完整保留'); bounds();
      button('关闭诊断').scrollIntoView({ block: 'nearest' });
      check(button('关闭诊断').getBoundingClientRect().bottom <= innerHeight, '窄矮视口关闭可达');
      await window.browserInput({ screenshot: 'diagnostics-' + innerHeight });
      await key('Escape'); check(!dialog() && document.activeElement === button('更多'), '诊断关闭恢复更多');
      await click('更多'); await click('导出设置'); check(dialog().contains(document.activeElement), '设置继续接收焦点');
      await key('Escape'); check(document.activeElement === button('更多'), '设置返回继续可用');
      document.getElementById('result').dataset.state = 'passed';
    } catch (error) { document.getElementById('result').dataset.state = 'failed'; document.getElementById('result').textContent = error.stack; } })();
  `, fixture, width!, height!);
});
