import { test } from 'node:test';
import { fixture } from './helpers/editing-fixture.js';
import { checkInteractiveBrowser } from './helpers/interactive-browser.js';

const script = String.raw`
import { act } from 'react';
import { createRoot } from 'react-dom/client';
import { App } from './src/panel/app.tsx';
import { state, deferred } from 'editing-fixture';
globalThis.IS_REACT_ACT_ENVIRONMENT = true;
const intervals = new Map(); let timer = 0;
window.setInterval = fn => { intervals.set(++timer, fn); return timer; }; window.clearInterval = id => intervals.delete(id);
const check = (v,m) => { if(!v) throw Error(m); };
const settle = () => new Promise(r => setTimeout(r, 80));
const action = async fn => { await act(async () => { await fn(); await settle(); }); await settle(); };
const button = text => [...document.querySelectorAll('button')].find(n => n.textContent === text || n.getAttribute('aria-label') === text);
const click = n => action(() => { check(n && !n.disabled,'入口可用'); n.focus(); n.click(); });
const key = key => action(() => window.browserInput({key}));
const editor = () => document.querySelector('[aria-label="文案全文"]');
const draft = () => document.querySelector('[aria-label="详情文案"]');
const input = (node, value) => action(() => { Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, 'value').set.call(node,value); node.dispatchEvent(new Event('input',{bubbles:true})); });
const cell = id => document.querySelector('[row-id="'+id+'"] [col-id="text"]');
const textClick = id => action(() => window.browserInput({pointer:{type:'mousePressed',x:cell(id).getBoundingClientRect().left+20,y:cell(id).getBoundingClientRect().top+20}}).then(() => window.browserInput({pointer:{type:'mouseReleased',x:cell(id).getBoundingClientRect().left+20,y:cell(id).getBoundingClientRect().top+20}})));
(async()=>{try {
 state.status.snapshot.segments.push({id:'second',order:2,text:'第二条',video:null});
 await action(()=>createRoot(document.getElementById('root')).render(<App/>));
 await textClick('segment'); await input(editor(),'第一条新文案');
 state.saveGate=deferred(); await textClick('second');
 check(state.segmentRequests.length===1 && state.segmentRequests[0].change.text==='第一条新文案','相邻点击先保存原行');
 await action(()=>{state.saveGate.resolve();state.saveGate=null;});
 check(editor()?.value==='第二条' && document.activeElement===editor(),'等待原行保存后一次点击进入相邻行');
 await key('Escape'); await click(button('查看片段 1 的详情')); await click(draft()); await input(draft(),'详情保存测试');
 await textClick('second'); state.segmentFailure=true; await click(button('保存并继续'));
 check(document.querySelector('[role="alertdialog"]') && draft().value==='详情保存测试' && document.body.textContent.includes('文案保存失败'),'保存失败保留目标、草稿与错误');
 state.segmentFailure=false; state.saveGate=deferred(); await click(button('保存并继续')); await key('Escape');
 check(document.querySelector('[role="alertdialog"]') && button('继续编辑').disabled,'保存中不能关闭或重复操作');
 await action(()=>{state.saveGate.resolve();state.saveGate=null;});
 check(!document.querySelector('[role="alertdialog"]') && editor()?.value==='第二条' && document.activeElement===editor(),'保存成功后完成原来的行内编辑意图');
 check(cell('segment').textContent==='详情保存测试','详情保存共用表格结果');
 await key('Escape'); await click(button('上一条片段')); await click(draft()); await input(draft(),'断线草稿');
 await action(()=>state.current.disconnect());
 check(draft().value==='断线草稿' && document.body.textContent.includes('详情草稿已保留'),'断线保留详情草稿并提示');
 state.status.snapshot.segments.find(item=>item.id==='segment').text='外部新文案';
 await click(button('保存文案'));
 check(draft().value==='断线草稿' && document.body.textContent.includes('不能覆盖新内容') && state.status.snapshot.segments.find(item=>item.id==='segment').text==='外部新文案','断线重存不能覆盖外部新内容');
 const removed=state.status.snapshot.segments.find(item=>item.id==='segment');
 state.status.snapshot.segments=state.status.snapshot.segments.filter(item=>item.id!=='segment');
 await action(()=>[...intervals.values()].forEach(fn=>fn()));
 check(draft()?.value==='断线草稿' && !draft().disabled && draft().readOnly && document.body.textContent.includes('仍可选中复制'),'删除目标后草稿仍可复制');
 await click(button('关闭详情')); await click(button('放弃修改'));
 state.status.snapshot.segments.unshift(removed); await action(()=>[...intervals.values()].forEach(fn=>fn()));
 check(!document.querySelector('aside'),'放弃断线草稿后正常关闭');
 const bounds=document.querySelector('.segment-grid').getBoundingClientRect().toJSON();
 await click(button('查找'));
 check(document.querySelector('.segment-grid').getBoundingClientRect().height===bounds.height,'浮动查找不压缩表格');
 state.status.snapshot.segments.push({id:'external-added',order:3,text:'别的面板新增',video:null});
 await click(button('新增口播片段（表格底部）'));
 check(state.status.snapshot.segments.length===4 && document.activeElement===draft() && draft().value==='','新增一次并打开真实新片段聚焦文案：'+JSON.stringify({count:state.status.snapshot.segments.length,active:document.activeElement?.outerHTML?.slice(0,250),draft:draft()?.outerHTML,body:document.body.textContent.slice(-500)}));
 check(!document.querySelector('[aria-label="查找文案"]'),'新增清除搜索障碍');
 await key('Escape'); check(document.activeElement?.closest('[row-id="created-'+state.saves+'"]'),'关闭新增详情回到新行');
 await action(()=>{state.batchFailure=true;}); await click(button('新增口播片段'));
 check(state.status.snapshot.segments.length===4 && !document.querySelector('aside') && document.body.textContent.includes('新增失败'),'创建失败不制造虚假行');
 state.batchFailure=false; await click(button('查看片段 2 的详情'));
 state.acquireGate=deferred(); await action(()=>window.browserInput({click:'[aria-label="详情文案"]'}));
 await click(button('查找')); const search=document.querySelector('[aria-label="查找文案"]'); search.focus();
 await action(()=>{state.acquireGate.resolve();state.acquireGate=null;});
 check(document.activeElement===search && !state.current,'迟到详情修改权释放且不抢查找焦点');
 document.getElementById('result').dataset.state='passed';
}catch(e){document.getElementById('result').dataset.state='failed';document.getElementById('result').textContent=e.stack;}})();
`;
test('片段草稿、连续行内编辑与新增共享真实保存结果', { timeout: 40000 }, t => checkInteractiveBrowser(t, script, fixture, 1200, 800));
