import { test } from 'node:test';
import { chrome } from './helpers/browser.js';
import { fixture } from './helpers/editing-fixture.js';
import { checkInteractiveBrowser } from './helpers/interactive-browser.js';

const script = String.raw`
import { act } from 'react';
import { createRoot } from 'react-dom/client';
import { App } from './src/panel/app.tsx';
import { state } from 'editing-fixture';
globalThis.IS_REACT_ACT_ENVIRONMENT = true;
const intervals = new Map(); let timer=0;
window.setInterval=callback=>{intervals.set(++timer,callback);return timer;}; window.clearInterval=id=>intervals.delete(id);
const check=(ok,message)=>{if(!ok)throw Error(message);};
const action=async fn=>{await act(async()=>{await fn();await new Promise(r=>setTimeout(r,80));});await new Promise(r=>setTimeout(r,180));};
const input=options=>action(()=>window.browserInput(options));
const clickHeader=name=>action(async()=>{
 const node=[...document.querySelectorAll('header button')].find(node=>(node.getAttribute('aria-label')??node.textContent)===name&&!node.hidden);
 check(node&&!node.disabled,'页头操作可用：'+name);
 const rect=node.getBoundingClientRect(); const position={x:rect.x+rect.width/2,y:rect.y+rect.height/2};
 await window.browserInput({pointer:{type:'mousePressed',...position}});
 await window.browserInput({pointer:{type:'mouseReleased',...position}});
});
const select=id=>input({click:'[row-id="'+id+'"] input[type="checkbox"]'});
const poll=()=>action(()=>[...intervals.values()].forEach(fn=>fn()));
const selected=ids=>check(JSON.stringify([...(state.selectionRequests.at(-1)??[])].sort())===JSON.stringify(ids),'勾选同步范围 '+ids);
(async()=>{try{
 state.status.snapshot.segments=[{id:'a',order:1,text:'第一段',video:null},{id:'b',order:2,text:'第二段',video:null},{id:'c',order:3,text:'第三段',video:null}];
 await action(()=>createRoot(document.getElementById('root')).render(<App/>));
 const geometry=()=>{const r=document.querySelector('.segment-grid').getBoundingClientRect();return JSON.stringify([r.top,r.height]);};
 const baseline=geometry();
 const stable=()=>{
  check(!document.querySelector('header h1').hidden,'勾选后标题仍可见');
  const buttons=[...document.querySelectorAll('header button')].filter(node=>node.getClientRects().length);
  check(buttons.map(node=>node.textContent).join('|')==='新增口播片段|查找|导出全片|更多','主入口保持稳定且无旧勾选栏');
  check(!document.querySelector('.organization')&&!document.querySelector('[aria-label="删除勾选"]')&&!document.querySelector('[aria-label^="项目顺序"]'),'旧操作栏及移动删除入口移除');
  check(geometry()===baseline,'勾选不推移表格或改变高度');
  check(document.documentElement.scrollWidth<=innerWidth,'页头无横向溢出');
  for(const node of buttons){const r=node.getBoundingClientRect();check(r.left>=0&&r.right<=innerWidth&&node.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)),'主入口可真实命中');}
 };
 stable(); await clickHeader('新增口播片段');
 check(JSON.stringify(state.segmentRequests.at(-1).change)==='{"text":""}','顶部新增继续发送无锚点的末尾追加请求');await poll();stable(); await select('a'); stable(); selected(['a']); await select('b'); stable(); selected(['a','b']);
 await window.browserInput({screenshot:'stable-selected-header'});
 await clickHeader('导出全片');
 check(state.exportRequests.length===1&&state.exportRequests[0].length===1,'全片导出仅传服务地址，不附带勾选范围');selected(['a','b']);
 await input({click:'header [aria-haspopup="dialog"]'});await input({key:'Escape'});
 check(!document.querySelector('dialog[open]')&&document.activeElement.textContent==='更多','Escape 仅关闭更多并返回稳定入口');selected(['a','b']);
 await input({click:'.search-trigger'});await input({key:'第'});
 check(document.querySelectorAll('.ag-row[row-id]').length===3,'查找保持全部片段');selected(['a','b']);
 await input({key:'Escape'});check(document.activeElement.classList.contains('search-trigger'),'关闭查找回到查找按钮');selected(['a','b']);stable();
 await input({click:'[row-id="b"] [col-id="text"]',button:'right'});
 await input({key:'Escape'});selected(['a','b']);check(!document.querySelector('[role="menu"]'),'Escape 关闭行菜单');
 await input({key:'Escape'});selected([]);stable();
 await input({click:'.ag-header input[type="checkbox"]'});selected(['a','b','c']);
 await input({click:'.ag-header input[type="checkbox"]'});selected([]);
 await select('a');await select('b');
 await input({click:'[row-id="a"] [col-id="text"]',button:'right'});
 check(document.querySelector('[role="menu"] [role="menuitem"]').textContent==='删除口播片段','菜单删除项名称明确');
 await input({click:'[role="menu"] [role="menuitem"]'});
 check(document.querySelector('[role="alertdialog"]').textContent.includes('2 个'),'新入口确认准确删除范围');
 await input({click:'[data-delete-confirm]'});
 check(state.batchRequests.at(-1).changes.map(change=>change.expected.id).join()==='a,b','确认后删除全部勾选');
 await poll();check(state.status.snapshot.segments.map(s=>s.id).join()==='c','保留未勾选片段');stable();
 await select('c');await action(()=>state.tableConnections.at(-1).resolve());
 check(!document.querySelector('.ag-row[aria-selected="true"]')&&document.querySelector('footer').textContent.includes('勾选连接已断开'),'断线清空勾选并保留恢复入口');
 await input({click:'footer [role="alert"] button'});await select('c');selected(['c']);
 state.selectionFailure=true;await select('c');
 check(!document.querySelector('.ag-row[aria-selected="true"]')&&document.querySelector('footer [role="alert"] button'),'同步失败清空选择且可以恢复');
 state.selectionFailure=false;await input({click:'footer [role="alert"] button'});stable();
 document.getElementById('result').dataset.state='passed';
}catch(error){document.getElementById('result').dataset.state='failed';document.getElementById('result').textContent=error.stack;}})();
`;
for(const width of [1600,420]) test('勾选前后主入口稳定且复选框及全片范围保持 '+width,{skip:chrome?false:'未执行：需要 Chrome/Chromium',timeout:40000},t=>checkInteractiveBrowser(t,script,fixture,width));
