import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { startService } from '../src/service/server.js';
import { createBusinessMcp } from '../src/mcp/server.js';
import { beginEdit, queryStatus } from '../src/shared/client.js';
import type { ServiceStatus, VideoAsset } from '../src/shared/contracts.js';

test('MCP 与表格共用视频导入和关联规则，预览支持范围播放且不开放任意文件', async t => {
  const root = mkdtempSync(join(tmpdir(), 'clapgrid-video-http-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const sourcePath = join(root, 'source.mp4');
  execFileSync('ffmpeg', ['-v', 'error', '-f', 'lavfi', '-i', 'color=c=red:s=64x48:d=1', '-c:v', 'libx264', sourcePath]);
  const panelDirectory = join(root, 'panel'); mkdirSync(panelDirectory);
  writeFileSync(join(panelDirectory, 'index.html'), 'ClapGrid');
  const service = await startService({ projectDirectory: join(root, 'project'), panelDirectory, port: 0 });
  t.after(() => service.close());
  const mcp = createBusinessMcp(service.url);
  const client = new Client({ name: '视频验证', version: '1' });
  t.after(() => client.close()); t.after(() => mcp.close());
  const [a, b] = InMemoryTransport.createLinkedPair();
  await mcp.connect(b); await client.connect(a);
  const imported = await client.callTool({ name: 'clapgrid_import_video', arguments: { sourcePath } });
  assert.notEqual(imported.isError, true);
  const asset = (imported.structuredContent as { asset: VideoAsset }).asset;
  const session = await beginEdit(service.url);
  const conflict = await client.callTool({ name: 'clapgrid_import_video', arguments: { sourcePath } });
  assert.equal(conflict.isError, true);
  assert.match(JSON.stringify(conflict.content), /用户正在编辑/);
  const userImport = await fetch(`${service.url}/api/video/import`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Edit-Token': session.token }, body: JSON.stringify({ sourcePath }) });
  assert.equal(userImport.status, 200);
  await session.close();
  await client.callTool({ name: 'clapgrid_modify', arguments: { changes: [{ kind: 'add', text: '视频测试' }] } });
  const before = await queryStatus(service.url);
  const linked = await client.callTool({ name: 'clapgrid_modify', arguments: { changes: [{ kind: 'video', expected: before.snapshot.segments[0], assetId: asset.id, start: 0.25 }] } });
  assert.equal((linked.structuredContent as { summary: { applied: number } }).summary.applied, 1);
  const latest = (linked.structuredContent as { status: ServiceStatus }).status;
  assert.deepEqual((await queryStatus(service.url)).snapshot, latest.snapshot);
  const thumbnail = await fetch(`${service.url}/api/media/${asset.id}/thumbnail`);
  assert.equal(thumbnail.headers.get('content-type'), 'image/png');
  assert.equal(thumbnail.status, 200);
  const preview = await fetch(`${service.url}/api/media/${asset.id}/preview`, { headers: { Range: 'bytes=0-15' } });
  assert.equal(preview.status, 206);
  assert.equal((await preview.arrayBuffer()).byteLength, 16);
  assert.equal(preview.headers.get('content-type'), 'video/webm');
  assert.equal((await fetch(`${service.url}/api/media/${asset.id}/source`)).status, 404);
  assert.equal((await fetch(`${service.url}/api/media/unknown/preview`)).status, 404);
  const unlinked = await client.callTool({ name: 'clapgrid_modify', arguments: { changes: [{ kind: 'video', expected: latest.snapshot.segments[0], assetId: null, start: 0 }] } });
  assert.equal((unlinked.structuredContent as { summary: { applied: number } }).summary.applied, 1);
});
